services:
  mongo-db:
    image: mongo:4.4.29
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 20

  springboot-service:
    image: wiaime/springboot-image-service:latest
    container_name: springboot-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/springbootimagesdb
      SERVER_PORT: "8080"
    depends_on:
      mongo-db:
        condition: service_healthy
    ports:
      - "8080:8080"

  flask-service:
    image: wiaime/flask-image-service:latest
    container_name: flask-service
    environment:
      MONGO_URI: mongodb://mongo-db:27017/image_db
      PORT: "5000"
    depends_on:
      mongo-db:
        condition: service_healthy
    ports:
      - "5000:5000"

volumes:
  mongo_data:
