name: CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Flask
        uses: docker/build-push-action@v6
        with:
          context: ./SpringBoot/Flask/flask-image-service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-image-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-image-service:${{ github.sha }}

      - name: Build & Push Spring
        uses: docker/build-push-action@v6
        with:
          context: ./SpringBoot/SpringBoot/imageupload
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/springboot-image-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/springboot-image-service:${{ github.sha }}
